### ISSUE TITLE
پخش نشدن ویدیو در اندروید ۴.۳

### ISSUE THREAD

**Issue by ahoogol** [tapsellorg/TapsellPlusSDK-AndroidSample#10]
من از تبلیغات ویدیویی جایزه ای شما استفاده کردم و کار می کنه. اما روی یکی از گوشی ها که نسخه اش ۴.۳ هست موقع نمایش ویدیو یک دیالوگ داخل اکتیویتی جدید باز میشه که نوشته امکان پخش ویدیو وجود نداره و بلافاصله بر می گرده تو اکتیویتی قبلی برنامه. این هم لاگی هس که انداخته:

> D/TapsellPlusCordova: Ad Opened
D/CordovaActivity: Paused the activity.
D/MediaPlayer_Java: [FXN.ASD] setDataSource :: uri = http://127.0.0.1:39410/https%3A%2F%2Fcdn.tapsell.ir%2Fcreative%2Ff66c7c5e-d4e1-4766-b57f-f513a13aaac4%2F1398-09-13%2F1575441860628%2524out_1.mp4
    Couldn't open file on client side, trying server side
E/MediaPlayer-JNI: [FXN][ASD]getVideoSurfaceTexture: null surface texture
E/MediaPlayer: error (1, -1004)
E/MediaPlayer_Java: Error (1,-1004)
D/VideoView: Error: 1,-1004
D/TapsellPlusCordova: Ad Closed
E/WindowManager: Activity ir.tapsell.sdk.TapsellAdActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41e19870 V.E..... R.....I. 0,0-480,213} that was originally added here
    android.view.WindowLeaked: Activity ir.tapsell.sdk.TapsellAdActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41e19870 V.E..... R.....I. 0,0-480,213} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:349)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:239)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
        at android.app.Dialog.show(Dialog.java:289)
        at android.app.AlertDialog$Builder.show(AlertDialog.java:966)
        at ir.tapsell.sdk.views.BaseVideoView$5.onError(Unknown Source)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2101)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5214)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
        at dalvik.system.NativeStart.main(Native Method)

مشخصات کامل دستگاه:
Sony Xperia M dual (C2005) - Android 4.3 (Jelly Bean)

**Comment by behdad222** [comment]
بررسی میکنم

**Comment by behrooz-fard** [comment]
android
