### ISSUE TITLE
NullPointerException on TapsellPlus 1.2.2

### ISSUE THREAD

**Issue by javadVatan** [tapsellorg/TapsellPlusSDK-AndroidSample#19]
### We have got NullPointerException on our CrashReporter 

Tapsell library version: **ir.tapsell.plus:tapsell-plus-sdk-android:1.2.2**
On Android versions : 8.1.0, 9, 10

`java.lang.NullPointerException: Attempt to invoke virtual method 'void ir.tapsell.plus.x.a.a.a(android.app.Activity, ir.tapsell.plus.l, java.lang.String, ir.tapsell.plus.x.a.c)' on a null object reference
    at ir.tapsell.plus.x.a.b.a(AdNetworkManager.java:67)
    at ir.tapsell.plus.v.lambda$-dH0n6rSd4m4qYvoap-o9EpI6VA(WaterfallManager.java:0)
    at ir.tapsell.plus.v.lambda$pTk4GlXxvDOdc2YaIeQym7c0hQA(WaterfallManager.java:0)
    at ir.tapsell.plus.v.a(WaterfallManager.java:16)
    at ir.tapsell.plus.v.e(WaterfallManager.java:19)
    at ir.tapsell.plus.v.lambda$-dH0n6rSd4m4qYvoap-o9EpI6VA(WaterfallManager.java:0)
    at ir.tapsell.plus.v.lambda$pTk4GlXxvDOdc2YaIeQym7c0hQA(WaterfallManager.java:0)
    at ir.tapsell.plus.v.a(WaterfallManager.java:26)
    at ir.tapsell.plus.v.lambda$-dH0n6rSd4m4qYvoap-o9EpI6VA(WaterfallManager.java:0)
    at ir.tapsell.plus.v.lambda$pTk4GlXxvDOdc2YaIeQym7c0hQA(WaterfallManager.java:0)
    at ir.tapsell.plus.v.a(WaterfallManager.java:96)
    at ir.tapsell.plus.v.lambda$-dH0n6rSd4m4qYvoap-o9EpI6VA(WaterfallManager.java:0)
    at ir.tapsell.plus.v.lambda$pTk4GlXxvDOdc2YaIeQym7c0hQA(WaterfallManager.java:0)
    at ir.tapsell.plus.v.a(WaterfallManager.java:2)
    at ir.tapsell.plus.v$a.a(WaterfallManager.java:3)
    at ir.tapsell.plus.x.g.c$a.a(TapsellImp.java:4)
    at ir.tapsell.plus.x.g.e$a.onError(TapsellRewardedVideo.java:2)
    at ir.tapsell.sdk.k.i$b.run
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8167)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

**Comment by behrooz-fard** [comment]
Hi dear Javad,
Sorry for the delay in response. We solved this bug in our last version. Please check our [document](https://docs.tapsell.ir/plus-sdk/android/main/).
