### ISSUE TITLE
SSL crash on android 4.4

### ISSUE THREAD

**Issue by mkfcga** [tapsellorg/TapsellPlusSDK-AndroidSample#47]
سلام. در تپسل پلاس نسخه 2.1.3 همچنان مشکل باز نشدن ویدیو و کرش اپ در اندروید 4.4 وجود دارد
04-19 17:30:24.605 7413-7520/? E/TAP_SDK_WaterfallManag: onWaterfallFailed: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x894a2dc0: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x73ebdce0:0x00000000)
04-19 17:30:24.635 3228-4110/? E/EnterpriseContainerManager: ContainerPolicy Service is not yet ready!!!
04-19 17:30:24.875 7413-7413/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: **, PID: 7413
java.lang.Error: FATAL EXCEPTION [main]
Unity version : 2020.3.16f1
Device model : samsung GT-I9500
Device fingerprint: **
Build Type : Release
Scripting Backend : IL2CPP
ABI : armeabi-v7a
Strip Engine Code : true

Caused by: java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd
    at com.google.unity.ads.UnityRewardedAd$1.run(UnityRewardedAd.java:53)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5356)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by mahdi-malv** [comment]
سلام
نسخه‌ی آخر ۲.۱.۷ هست که این فیکس رو داره

**Comment by mkfcga** [comment]
سلام وقت بخیر.بله نسخه آخره
    On Wednesday, April 20, 2022, 10:39:15 PM GMT+4:30, Mahdi Malvandi ***@***.***> wrote:  
 
 


سلام
نسخه‌ی آخر ۲.۱.۷ هست که این فیکس رو داره

**Comment by mkfcga** [comment]
در نسخه اخر مشکل حل شده
