### ISSUE TITLE
🐛  باگ: مشکل در نمایش تبلیغات بنری همسان

### ISSUE THREAD

**Issue by AlirezaIvaz** [tapsellorg/TapsellPlusSDK-AndroidSample#86]
تبلیغات بنری همسان رو براساس مستندات و با **ویو پیش‌فرض** پیاده‌سازی کردم اما موقع اجرا با این خطا مواجه می‌شم:
```
Error inflating class com.google.android.gms.ads.nativead.NativeAdView Caused by: java.lang.ClassNotFoundException: Didn’t find class “com.google.android.gms.ads.nativead.NativeAdView"
```
توی خطاهای فنی رایج گفته شده بود علت خطا اینه که از ادنتورک ادموب استفاده شده و دیپندنسیش اضافه نشده درصورتی که اینطوری نیست و از ادموب استفاده نشده و با اضافه کردن دیپندنسی هم کتابخونه ادموب به خاطر init نشدن کرش می‌کنه.

کرش لاگ:
```
android.view.InflateException: Binary XML file line #5 in com.example:layout/native_banner: Binary XML file line #5 in com.example:layout/native_banner: Error inflating class com.google.android.gms.ads.nativead.NativeAdView
    Caused by: android.view.InflateException: Binary XML file line #5 in com.example:layout/native_banner: Error inflating class com.google.android.gms.ads.nativead.NativeAdView
    Caused by: java.lang.ClassNotFoundException: com.google.android.gms.ads.nativead.NativeAdView
    	at java.lang.Class.classForName(Native Method)
    	at java.lang.Class.forName(Class.java:536)
    	at android.view.LayoutInflater.createView(LayoutInflater.java:843)
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1034)
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:989)
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:673)
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
    	at ir.tapsell.sdk.nativeads.TapsellNativeBannerViewManager.createViewHolder(Unknown Source:7)
    	at ir.tapsell.sdk.nativeads.TapsellNativeBannerViewManager.createAdView(Unknown Source:2)
    	at ir.tapsell.sdk.nativeads.TapsellNativeBannerManager$Builder.inflateTemplate(Unknown Source:35)
    	at ir.tapsell.plus.f.a(Unknown Source:17)
    	at ir.tapsell.plus.NativeManager.a(Unknown Source:2)
    	at ir.tapsell.plus.adNetworks.tapsell.TapsellNativeAd.d(Unknown Source:22)
    	at ir.tapsell.plus.adNetworks.tapsell.TapsellNativeAd.$r8$lambda$6CLiUWOCTvdqVt8EN8wCXRQFXSc(Unknown Source:0)
    	at ir.tapsell.plus.adNetworks.tapsell.TapsellNativeAd$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    	at android.os.Handler.handleCallback(Handler.java:958)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loopOnce(Looper.java:230)
    	at android.os.Looper.loop(Looper.java:319)
    	at android.app.ActivityThread.main(ActivityThread.java:8893)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.nativead.NativeAdView" on path: DexPathList[[zip file "/data/app/~~kcAiIl3ceXIefvRIEA3XRg==/com.example-wUn2CwQWOw3t62ITJiKlyg==/base.apk"],nativeLibraryDirectories=[/data/app/~~kcAiIl3ceXIefvRIEA3XRg==/com.example-wUn2CwQWOw3t62ITJiKlyg==/lib/arm64, /data/app/~~kcAiIl3ceXIefvRIEA3XRg==/com.example-wUn2CwQWOw3t62ITJiKlyg==/base.apk!/lib/arm64-v8a, /system/lib64]]
    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	at java.lang.Class.classForName(Native Method) 
    	at java.lang.Class.forName(Class.java:536) 
    	at android.view.LayoutInflater.createView(LayoutInflater.java:843) 
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1034) 
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:989) 
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:673) 
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:544) 
    	at ir.tapsell.sdk.nativeads.TapsellNativeBannerViewManager.createViewHolder(Unknown Source:7) 
    	at ir.tapsell.sdk.nativeads.TapsellNativeBannerViewManager.createAdView(Unknown Source:2) 
    	at ir.tapsell.sdk.nativeads.TapsellNativeBannerManager$Builder.inflateTemplate(Unknown Source:35) 
    	at ir.tapsell.plus.f.a(Unknown Source:17) 
    	at ir.tapsell.plus.NativeManager.a(Unknown Source:2) 
    	at ir.tapsell.plus.adNetworks.tapsell.TapsellNativeAd.d(Unknown Source:22) 
    	at ir.tapsell.plus.adNetworks.tapsell.TapsellNativeAd.$r8$lambda$6CLiUWOCTvdqVt8EN8wCXRQFXSc(Unknown Source:0) 
    	at ir.tapsell.plus.adNetworks.tapsell.TapsellNativeAd$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
    	at android.os.Handler.handleCallback(Handler.java:958) 
    	at android.os.Handler.dispatchMessage(Handler.java:99) 
    	at android.os.Looper.loopOnce(Looper.java:230) 
    	at android.os.Looper.loop(Looper.java:319) 
    	at android.app.ActivityThread.main(ActivityThread.java:8893) 
    	at java.lang.reflect.Method.invoke(Native Method) 
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
```
تبلیغات بنری همسان فقط در ادنتورک ادموب قابل استفاده هستن؟

**Comment by MortezaNedaei** [comment]
سلام ممنون از گزارش خطا.
تبلیغ نیتیو تپسل، به کتابخانه `play-services-ads` وابستگی داره و لازمه اضافه‌ش کنید. 
میتونید از کلید تست ادموب که در اپ سمپل هست، استفاده کنید. 
این مورد رو در مستندات اضافه میکنیم.
