### ISSUE TITLE
🐛 [ERROR]  GoogleApiManager

### ISSUE THREAD

**Issue by AmirSinaRZ** [tapsellorg/TapsellPlusSDK-AndroidSample#97]
```
2024-10-02 08:27:06.959  5620-5837  GoogleApiManager        ir.sina.sketchbox                    E  Failed to get service from broker. 
                                                                                                    java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2995)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2920)
                                                                                                    	at amok.a(:com.google.android.gms@243633029@24.36.33 (190400-675378931):36)
                                                                                                    	at ammr.z(:com.google.android.gms@243633029@24.36.33 (190400-675378931):143)
                                                                                                    	at altt.run(:com.google.android.gms@243633029@24.36.33 (190400-675378931):54)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at bqoh.ml(:com.google.android.gms@243633029@24.36.33 (190400-675378931):1)
                                                                                                    	at bqoh.dispatchMessage(:com.google.android.gms@243633029@24.36.33 (190400-675378931):5)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by MortezaNedaei** [comment]
این مشکل مربوط به کتابخانه تپسل نیست و از یکی از کتابخانه های گوگل مثل ادموب یا فایربیس داره اتفاق میوفته
در نظر داشته باشید که کتابخانه های تپسل و گوگل رو به نسخه های جدیدتر آپدیت کنید
لینک issueها:
https://github.com/firebase/firebase-android-sdk/issues/5024
https://groups.google.com/g/google-admob-ads-sdk/c/ssMEULn20YM?pli=1
